apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-glusterfs-storage
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://lb.unixway.com:32689"
  clusterid: "a586dfa6bf98379a18a78ccaace03539"
  restuser: "admin"
  secretNamespace: "kube-glusterfs"
  secretName: "heketi-secret"
  volumetype: "replicate:3"
