apiVersion: v1
kind: Namespace
metadata:
  name: kube-glusterfs
---
kind: Service
apiVersion: v1
metadata:
  name: heketi
  namespace: kube-glusterfs
spec:
  type: NodePort
  selector:
    app: heketi
  ports:
  - name: heketi
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: heketi-secret
  namespace: kube-glusterfs
data:
  key: cGFzc3dvcmQ=
type: kubernetes.io/glusterfs
---
apiVersion: v1
kind: Secret
metadata:
  name: heketi-ssh-key
  namespace: kube-glusterfs
type: Opaque
data:
  id_rsa: ***
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: heketi
  namespace: kube-glusterfs
spec:
  selector:
    matchLabels:
      app: heketi
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: heketi
      labels:
        app: heketi
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - image: heketi/heketi:5
        imagePullPolicy: Always
        name: heketi
        env:
        - name: HEKETI_EXECUTOR
          value: ssh
        - name: HEKETI_SSH_USER
          value: root
        - name: HEKETI_SSH_PORT
          value: '22'
        - name: HEKETI_SSH_KEYFILE
          value: "/root/.ssh/id_rsa"
        - name: HEKETI_ADMIN_KEY
          valueFrom:
            secretKeyRef:
              name: heketi-secret
              key: key
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: heketi-ssh-key
          mountPath: "/root/.ssh"
        - name: heketi-db
          mountPath: "/var/lib/heketi"
        readinessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 3
          httpGet:
            path: "/hello"
            port: 8080
        livenessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 15
          httpGet:
            path: "/hello"
            port: 8080
      volumes:
      - name: heketi-ssh-key
        secret:
          secretName: heketi-ssh-key
          defaultMode: 0400
      - name: heketi-db
        emptyDir:
          medium: "Memory"
          sizeLimit: "1Gi"
